### ISSUE TITLE
Code Overhaul

### ISSUE THREAD

**Issue by 0-x-P** [KayleMine/wor-tortle#2]
They released a new version. Oddly, they still have it labeled as 8.6, but offsets and other things have been changed.

File name also changed from functions.ballistics to functions.ex_ballistics for something.

**Comment by KayleMine** [comment]
https://github.com/KayleMine/wor-tortle/commit/229b25a5f6d58e0a6ef147fd74b578531f238d08

**Comment by mime-r** [comment]
> They released a new version. Oddly, they still have it labeled as 8.6, but offsets and other things have been changed.
> 
> File name also changed from functions.ballistics to functions.ex_ballistics for something.

The run.py file seems to import functions.ex_ballistics now but there isn't such a file in the module folder. Is this file going to be added in the future? Or is there something I'm missing for this to run.

**Comment by KayleMine** [comment]
> > They released a new version. Oddly, they still have it labeled as 8.6, but offsets and other things have been changed.
> > File name also changed from functions.ballistics to functions.ex_ballistics for something.
> 
> The run.py file seems to import functions.ex_ballistics now but there isn't such a file in the module folder. Is this file going to be added in the future? Or is there something I'm missing for this to run.


make folder update near update cmd and run it, then move files from update folder to pyp\module
