### ISSUE TITLE
start.cmd frozen?

### ISSUE THREAD

**Issue by sigmaskibidifortnite23** [KayleMine/wor-tortle#8]
@
![Screenshot 2024-07-03 160632](https://github.com/KayleMine/wor-tortle/assets/174651453/a3f24df7-0c09-44a9-95f8-23c797ef6620)
when i open start.cmd it only prints 

[>] Welcome to WC Loader

doesnt print anything else even after leaving it open for a while

**Comment by KayleMine** [comment]
When this pop-up, go back in game, its started.
